/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabajadoresRouteImport } from './routes/trabajadores'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as PaquetesRouteImport } from './routes/paquetes'
import { Route as MovimientosRouteImport } from './routes/movimientos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComisionesRouteImport } from './routes/comisiones'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as IndexRouteImport } from './routes/index'

const TrabajadoresRoute = TrabajadoresRouteImport.update({
  id: '/trabajadores',
  path: '/trabajadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const PaquetesRoute = PaquetesRouteImport.update({
  id: '/paquetes',
  path: '/paquetes',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimientosRoute = MovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComisionesRoute = ComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caja': typeof CajaRoute
  '/comisiones': typeof ComisionesRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/paquetes': typeof PaquetesRoute
  '/reportes': typeof ReportesRoute
  '/trabajadores': typeof TrabajadoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caja': typeof CajaRoute
  '/comisiones': typeof ComisionesRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/paquetes': typeof PaquetesRoute
  '/reportes': typeof ReportesRoute
  '/trabajadores': typeof TrabajadoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caja': typeof CajaRoute
  '/comisiones': typeof ComisionesRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/paquetes': typeof PaquetesRoute
  '/reportes': typeof ReportesRoute
  '/trabajadores': typeof TrabajadoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caja'
    | '/comisiones'
    | '/login'
    | '/movimientos'
    | '/paquetes'
    | '/reportes'
    | '/trabajadores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caja'
    | '/comisiones'
    | '/login'
    | '/movimientos'
    | '/paquetes'
    | '/reportes'
    | '/trabajadores'
  id:
    | '__root__'
    | '/'
    | '/caja'
    | '/comisiones'
    | '/login'
    | '/movimientos'
    | '/paquetes'
    | '/reportes'
    | '/trabajadores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CajaRoute: typeof CajaRoute
  ComisionesRoute: typeof ComisionesRoute
  LoginRoute: typeof LoginRoute
  MovimientosRoute: typeof MovimientosRoute
  PaquetesRoute: typeof PaquetesRoute
  ReportesRoute: typeof ReportesRoute
  TrabajadoresRoute: typeof TrabajadoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabajadores': {
      id: '/trabajadores'
      path: '/trabajadores'
      fullPath: '/trabajadores'
      preLoaderRoute: typeof TrabajadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paquetes': {
      id: '/paquetes'
      path: '/paquetes'
      fullPath: '/paquetes'
      preLoaderRoute: typeof PaquetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimientos': {
      id: '/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof MovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comisiones': {
      id: '/comisiones'
      path: '/comisiones'
      fullPath: '/comisiones'
      preLoaderRoute: typeof ComisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CajaRoute: CajaRoute,
  ComisionesRoute: ComisionesRoute,
  LoginRoute: LoginRoute,
  MovimientosRoute: MovimientosRoute,
  PaquetesRoute: PaquetesRoute,
  ReportesRoute: ReportesRoute,
  TrabajadoresRoute: TrabajadoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
